### ISSUE TITLE
j04 dames

### ISSUE THREAD

**Issue by floklein** [jzck/42-correction-jhalford#2]
Ton test fonctionne pas pour les 2 exercices sur les Dames. Ma version passe la Moulinette (a voir sur mon Git), mais ton test affiche une erreur. ++

**Comment by Harly2018** [comment]
Cool...
Donc t'es bien avancé surtout si tu l'execuse sans probleme...
Car la moulitte c'est deja une bonne nouvelle...

**Comment by jzck** [comment]
cf #3 je ne maintiens plus rien moi-meme.
